app:
  name: geocoder

microservices:
  ads_url: http://localhost:3000/api/v1

rabbit_mq:
  consumer_pool: 10
  host: <%= ENV['RABBITMQ_HOST']%>
  username: <%= ENV['RABBITMQ_USER']%>
  password: <%= ENV['RABBITMQ_PASSWORD']%>

logger:
  path: log/app.log
  level: info
